services:
  db:
    image: postgres:15
    container_name: hyperbrowser-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hyperbrowser
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hyperbrowser-bot
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    working_dir: /app
    command: ["python", "src/main.py"]
    restart: unless-stopped

volumes:
  pgdata: